# Generated by Django 5.2.5 on 2025-08-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
