# Generated by Django 5.2.5 on 2025-08-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_test', '0002_image_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_storage',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
